# Generated by Django 6.0.1 on 2026-01-28 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('A4', 'A4ポスター'), ('TCG', 'トレーディングカード')], max_length=10, verbose_name='種別')),
                ('name', models.CharField(max_length=255, verbose_name='商品名')),
                ('price', models.IntegerField(default=88, verbose_name='金額')),
                ('image', models.ImageField(upload_to='products/', verbose_name='画像')),
                ('is_archived', models.BooleanField(default=False, verbose_name='保管庫送り')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '全商品一覧',
            },
        ),
    ]
