# Generated by Django 6.0.1 on 2026-01-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='A4Archive',
            fields=[
            ],
            options={
                'verbose_name': '保管庫',
                'verbose_name_plural': 'A4サイズポスター保管庫',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.product',),
        ),
        migrations.CreateModel(
            name='A4Poster',
            fields=[
            ],
            options={
                'verbose_name': '商品一覧',
                'verbose_name_plural': 'A4サイズポスター',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.product',),
        ),
        migrations.CreateModel(
            name='TCGArchive',
            fields=[
            ],
            options={
                'verbose_name': '保管庫',
                'verbose_name_plural': 'トレーディングカード保管庫',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.product',),
        ),
        migrations.CreateModel(
            name='TCGCard',
            fields=[
            ],
            options={
                'verbose_name': '商品一覧',
                'verbose_name_plural': 'トレーディングカード',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.product',),
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '全商品一覧', 'verbose_name_plural': '全商品一覧'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('A4', 'A4サイズポスター'), ('TCG', 'トレーディングカード')], max_length=10, verbose_name='種別'),
        ),
    ]
