# Generated by Django 6.0.1 on 2026-01-28 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_a4archive_a4poster_tcgarchive_tcgcard_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='A4Archive',
        ),
        migrations.DeleteModel(
            name='A4Poster',
        ),
        migrations.DeleteModel(
            name='TCGArchive',
        ),
        migrations.DeleteModel(
            name='TCGCard',
        ),
        migrations.CreateModel(
            name='A4_1_Poster',
            fields=[
            ],
            options={
                'verbose_name': '商品一覧',
                'verbose_name_plural': '商品一覧',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.product',),
        ),
        migrations.CreateModel(
            name='A4_2_Archive',
            fields=[
            ],
            options={
                'verbose_name': '保管庫',
                'verbose_name_plural': '保管庫',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.product',),
        ),
    ]
