# Generated by Django 6.0.1 on 2026-01-28 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_delete_a4archive_delete_a4poster_delete_tcgarchive_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='A4_1_Poster',
        ),
        migrations.DeleteModel(
            name='A4_2_Archive',
        ),
        migrations.CreateModel(
            name='A_ProductList_A4',
            fields=[
            ],
            options={
                'verbose_name': '商品一覧',
                'verbose_name_plural': '商品一覧',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.product',),
        ),
        migrations.CreateModel(
            name='B_Archive_A4',
            fields=[
            ],
            options={
                'verbose_name': '保管庫',
                'verbose_name_plural': '保管庫',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.product',),
        ),
    ]
