# Generated by Django 6.0.1 on 2026-01-28 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_delete_a4_1_poster_delete_a4_2_archive_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='A_ProductList_A4',
        ),
        migrations.DeleteModel(
            name='B_Archive_A4',
        ),
        migrations.CreateModel(
            name='Show_ProductList_A4',
            fields=[
            ],
            options={
                'verbose_name': '商品一覧',
                'verbose_name_plural': '商品一覧',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.product',),
        ),
        migrations.CreateModel(
            name='Z_Archive_A4',
            fields=[
            ],
            options={
                'verbose_name': '保管庫',
                'verbose_name_plural': '保管庫',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.product',),
        ),
    ]
