# Generated by Django 6.0.1 on 2026-01-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_delete_a_productlist_a4_delete_b_archive_a4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='商品名')),
                ('price', models.IntegerField(verbose_name='売上金額')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='種別')),
                ('sold_at', models.DateTimeField(auto_now_add=True, verbose_name='販売日時')),
            ],
            options={
                'verbose_name': '売上データ',
                'verbose_name_plural': '売上データ一覧',
            },
        ),
        migrations.CreateModel(
            name='Show_ProductList_TCG',
            fields=[
            ],
            options={
                'verbose_name': '商品一覧',
                'verbose_name_plural': '商品一覧',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.product',),
        ),
        migrations.CreateModel(
            name='Z_Archive_TCG',
            fields=[
            ],
            options={
                'verbose_name': '保管庫',
                'verbose_name_plural': '保管庫',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.product',),
        ),
    ]
